.TH PSP 8 "6 June 2005" "iproute2" "Linux"
.SH 名前
PSP \- Precise Software Pacer
.SH 書式
.B tc qdisc ... dev
dev
.B  ( parent
classid 
.B | root) [ handle 
major: 
.B ] psp [ default 
.B ] [ rate
rate
.B ]

.B tc class ... dev
dev
.B parent 
major:[minor]
.B [ classid 
major:minor
.B ] psp rate
rate
.B ] [ mode 
mode
.B ] 

.SH 説明
Precise Software Pacer (PSPacer) は，パケット間ギャップ(IPG: Inter Packet 
Gap)を調整することによって精密なペーシングを提供するパケットスケジューラである．
本スケジューラは，
.BR tc (8) 
コマンドによるトラヒック制御から利用可能なクラスフルキューイング規則
(queuing disipline)として実装されており，各クラスごとに設定した送信ターゲットレート
にしたがってトラヒックを平滑化する．

ターゲットレートの指定方法には，
.BR tc (8)
コマンドから静的に指定する静的ターゲットレートモードと，TCPの場合に限り，輻輳ウィンドウ
サイズとラウンドトリップタイムから送信レートを見積もる動的ターゲットレートモードが
利用できる．

.SH ペーシングアルゴリズム
MTUが1500バイトで送信レートを半分にペーシングするには，IPGを1500バイトにする必要がある．
そこで，他のクラスにパケットがキューイングされている場合はそのパケットを利用し，存在しない
場合にはギャップパケットを送信する．

ギャップパケットは IEEE 802.3x フロー制御で定義された PAUSE パケットを利用し，必要な
IPG に合わせてサイズを調整したパケットである．ギャップパケットは送信ホストの直近の
スイッチまたはルータで消滅するので，外のネットワークには流れない．

PSP qdisc 内に，ペーシングするトラヒックとペーシングしないトラヒックが存在する場合は，
ターゲットレート以内でペーシングするトラヒックを優先して送信する．

.SH クラシフィケーション
PSP qdisc は CBQ のような階層的なクラス構造を持つことが可能であり，リーフノードの
各クラスはそれぞれ qdisc を持つ．

PSP qdisc にパケットがエンキューされると，ルートから開始して，次に示す方法にしたがい，
どのノードにパケットを分類するか決定する．これをリーフノードに達するまで繰り返す．
.TP
(i)
クラスに登録されたフィルタを調べ，条件が成立したノードへ送る．
.TP
(ii)
どの条件にも合致しなかった場合は，デフォルトクラスへ送る．

.SH QDISC
PSP クラスツリーのルート qdisc は，次のパラメータを持つ．

.TP 
parent major:minor | root
必須パラメータ．qdisc の親クラスを指定する．親クラスはインタフェースのルート，
もしくは既存のクラスのどちらかになる．
.TP
handle major:
qdisc にハンドルを割り当てる．ハンドルはメジャー番号にコロンをつなげた表記で表される．
ハンドルは qdisc を参照する際に使用されるため，サブクラスを設定する場合に必要となる．
.TP 
default minor-id
クラシフィケーションされなかったトラヒックはこのマイナー番号を持つクラスに送られる．
.TP 
rate rate
インタフェースの最大転送レートを明示的に指定する．
PCI バスボトルネックでインタフェースの物理性能を出せない場合に利用する．

.SH CLASSES
クラスは次に示すパラメータを保持する．

.TP 
parent major:minor
必須パラメータ．クラスの親クラスを指定する．クラスではなく，直接 qdisc に追加する場合は，
マイナー番号を省略する．
.TP 
classid major:minor
必須パラメータ．qdisc のように，クラスにも名前を付けることができる．子供(クラス，
qdisc)から参照されるために必要である．メジャー番号は所属する qdisc のメジャー番号と
等しくなければならない．
.TP 
rate rate
最大送信レートを指定する．使用できる単位については，
.BR tc (8)
の UNITS を参照のこと．
.TP
mode mode
動作モードを指定する．0から2の整数値を取る．0はペーシングなし，1は静的ターゲットレートによる
ペーシング，2は動的ターゲットレートによるペーシングである．

.SH 例
eth0 の出力帯域を 500Mbps に制限する:
.in +5
 # tc qdisc add dev eth0 root handle 1: psp default 1
 # tc class add dev eth0 parent 1: classid 1:1 psp rate 500mbit
 # tc qdisc add dev eth0 parent 1:1 handle 10: pfifo

.SH 制限事項
.TP
o
バージョン 1.0 は，動的ターゲットレートモードに対応していない．
.TP
o
TCP Segmentation Offloading (TSO) に対応していない．次のように
.BR ethtool (8)
を使って，TSO を無効化すること．
.in +5
# /sbin/ethtool -K eth0 tso off

.SH 出典
.TP
o
http://www.gridmpi.org/
.TP
o
R.Takano, T.Kudoh, Y.Kodama, M.Matsuda, H.Tezuka, and Y.Ishikawa,
"Design and Evaluation of Precise Software Pacing Mechanisms for 
Fast Long-Distance Networks," PFLDnet05, 2005.

.SH 関連項目
.BR tc (8)

.SH 著者
Ryousei Takano <takano-ryousei@aist.go.jp>.


