#! /bin/sh
# postrm script for shfs

set -e

case "$1" in
       purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

	set +e
	/sbin/depmod -a
	set -e
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

#DEBHELPER#

exit 0
