#! /bin/sh
# postinst script for shfs

set -e

case "$1" in
    configure)
	set +e
	/sbin/depmod -a
	set -e
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
